# Generated by Django 5.2.14 on 2026-05-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва організації')),
                ('resources', models.TextField(verbose_name='Ресурси')),
                ('volunteers_count', models.IntegerField(verbose_name='Кількість волонтерів')),
                ('projects', models.TextField(verbose_name='Проекти')),
            ],
        ),
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва збору')),
                ('description', models.TextField(verbose_name='Опис збору')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to='ngo_app.organization')),
            ],
        ),
    ]
